name: babysafe
description: Aplicativo de monitoramento de saúde infantil
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  device_preview: ^1.2.0
  intl: ^0.19.0
  permission_handler: ^11.0.0
  flutter_vlc_player: ^7.2.0
  http: ^0.13.6
  flutter_local_notifications: ^17.2.3
  flutter_mjpeg: ^2.0.2
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/babysafe_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/baby_icon.png"